/**
 * Git hook template generator
 */

import { AI_PATTERN, DEFAULT_AI_PATTERNS } from '../types.js';

export interface HookTemplateOptions {
  patterns?: readonly AI_PATTERN[];
}

/**
 * Generate bash hook content for removing AI co-authors
 */
export function generateHookContent(options: HookTemplateOptions = {}): string {
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;

  const sedCommands = patterns
    .map((p) => `sed -i -E '/${p.pattern}/d' "$COMMIT_MSG_FILE"`)
    .join('\n');

  return `#!/bin/bash
# nococli: Remove AI co-author signatures from commit messages
# Generated by noco (https://github.com/doanbactam/noco)

COMMIT_MSG_FILE=$1

# Remove AI co-author lines
${sedCommands}

# Remove trailing empty lines (handles whitespace-only lines too)
sed -i -e :a -e '/^[[:space:]]*$/{$d;N;ba' -e '}' "$COMMIT_MSG_FILE"
`;
}

/**
 * Get list of default AI patterns
 */
export function getDefaultPatterns(): readonly AI_PATTERN[] {
  return DEFAULT_AI_PATTERNS;
}

/**
 * Get list of pattern names for display
 */
export function getPatternNames(): string[] {
  return DEFAULT_AI_PATTERNS.map((p) => p.name);
}
